name: Compile Deno

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  release_metadata:
    name: Get Release Upload Metadata
    runs-on: self-hosted
    outputs:
      upload_url: ${{ steps.get_upload_metadata.outputs.upload_url }}
      prerelease: ${{ steps.get_upload_metadata.outputs.prerelease }}
      version: ${{ steps.get_upload_metadata.outputs.version }}
    steps:
      - id: get_upload_metadata
        run: |
          export VERSION="${{ github.event.inputs.version || github.ref }}"
          VERSION="${VERSION#refs/tags/}"
          response=$(curl -s -H "Accept: application/json" https://api.github.com/repos/soedirgo/deno-arm64/releases)
          release=$(echo $response | jq ".[]|select(.tag_name==\"${VERSION}\")")
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=upload_url::$(echo $release | jq -r '.upload_url')"
          echo "::set-output name=prerelease::$(echo $release | jq -r '.prerelease')"
  compile:
    runs-on: self-hosted
    needs: release_metadata
    name: "Compile"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile Deno
        run: |
          sudo apt-get update -y && sudo apt-get install -y zip unzip
          echo "Compiling Deno version ${GITHUB_REF#refs/tags/}"
          sudo docker build -t deno-build --build-arg DENO_VERSION=${GITHUB_REF#refs/tags/} --file ./Dockerfile.compile .
          sudo docker run --rm -v $(pwd):/pwd deno-build cp /deno/target/release/deno /pwd/
          zip deno-linux-arm64.zip ./deno
      - name: Upload Release Asset
        id: upload-release-asset-deno
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release_metadata.outputs.upload_url }}
          asset_path: ./deno-linux-arm64.zip
          asset_name: deno-linux-arm64.zip
          asset_content_type: application/zip
  build-docker:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: [ release_metadata, compile ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        if: |
          !startsWith("canary-", "${{ needs.release_metadata.outputs.version }}")
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=${{ needs.release_metadata.outputs.version }}
          tags: |
            soedirgo/deno:${{ needs.release_metadata.outputs.version }}
            soedirgo/deno:latest
      - name: Build and push (Canary)
        uses: docker/build-push-action@v2
        if: startsWith("canary-", "${{ needs.release_metadata.outputs.version }}")
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=${{ needs.release_metadata.outputs.version }}
          tags: |
            soedirgo/deno:${{ needs.release_metadata.outputs.version }}
